# gem install google-spreadsheet-ruby 

GOOGLE_USER="someone@gmail.com"
GOOGLE_PASSWORD="your_password"
GOOGLE_DOC_ID="01234567890123456789012345678901234567890123"
PBWORKS_API_KEY="xyz"
PBWORKS_WIKI_PAGE="sfhacks2013"

require 'rubygems'
require 'net/http'
require 'uri'
require 'google_spreadsheet'
require 'erb'

def links(html)
  html.gsub!(/beginninganchor1(?!http)/, 'beginninganchor1http://')
  html.gsub!('beginninganchor1', '<a href="')
  html.gsub!('beginninganchor2', '">')
  html.gsub!('endinganchor', '</a>')
  html
end

def format(text)
  text = 
  :ext
end


# CHANGE THIS LINE TO YOUR GMAIL LOGIN DETAILS:
session = GoogleSpreadsheet.login(GOOGLE_USER, GOOGLEPASSWORD)
rows = session.spreadsheet_by_url("https://spreadsheets.google.com/feeds/worksheets/#{GOOGLE_DOC_ID}/private/full").worksheets[0].rows
fields = rows[0]
data = rows.slice(1,rows.size).map { |row| data={} ; fields.zip(row).each { |f,r| data[f] = r } ; data }
template = ERB.new <<-EOF
<ul>
<% data.each_with_index { |row, idx| %>
<li><a href="#hack_<%= idx %>"><%= row['Hack Name'] %></a></li>
<% } %>
</ul>

<% data.each_with_index { |row, idx| %>
<br><br><hr>
<h1 id="hack_<%= idx %>"><%= row['Hack Name'] %></h1>
<h2>Creators: <%= row['Creators'] %></h2>
<br>
<p><%= row['About the hack'].gsub(/\n/,"<br />") %></p>
<p><b>APIs, data and tools used: </b><%= links(row['What APIs, data, tools, hardware or kit did you use?'].gsub(/\n/,"<br />")) %></p>
<p><b>Screenshots, photos and videos: </b><%= links(row['Screenshots, photos, audio or video of your hack'].gsub(/\n/,"<br />")) %></p>
<p><b>Source code and links: </b><%= links(row['Source code and links'].gsub(/\n/,"<br />")) %></p>
<p><b>Hack URL: </b><%= links(row['Hack URL'].gsub(/\n/,"<br />")) %></p>
<% } %>
EOF

html = "This page is generated by a script once a minute. Please don't edit it or your edits will be lost.<br><br>"
html += template.result(binding)
puts html
url = "http://sciencehackday.pbworks.com/api_v2/op/PutPage/page/#{PBWORKS_WIKI_PAGE}/write_key/#{PBWORKS_API_KEY}"
Net::HTTP.post_form(URI.parse(url), { "html" => html })

